### PR TITLE
switch default styles to mixins for overwrite capability

### PR DESCRIPTION
**Pull request by cooperwfloyd**
switched default styles to mixins for overwriting capability and moved a couple of blocks to `normalize` that made more sense there. no style changes, just sass structure https://kni-scss-git-type-mixins-kni.vercel.app/.

## Required items for every merge

- [x] Update `package.json` and `package-lock.json` version accordingly.

### CODE REVIEW

**Comment by dbox** [comment]
Can you show me what an overwrite might look like?

**Comment by cooperwfloyd** [comment]
yeah @dbox

**/src/styles/scss/01-config** 👇 
```scss
// all variable overrides go above config import
$siteMax--desktop: 1440;

@import 'node_modules/kni-scss/scss/01-config';

// all mixin and function overrides go below config import
@mixin h1 {
  @include setType(40, 56);
}

@mixin h2 {
 .....
}

@mixin h3 {
 .....
}
```

**/src/styles/scss/02-base** 👇 
```scss
@import 'node_modules/kni-scss/scss/02-base';

// any base style / normalize overrides go below the base import
img {
  display: inline-block;
}
```

**Comment by dbox** [comment]
So mixin overrides = no repeated code?

**Review by dbox — APPROVED** [review]

**Comment by cooperwfloyd** [comment]
@dbox correct!

**Pull request merged**
